config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :dashboard  do
    resources :categories, except: :show
    resources :questions, except: :show
    resources :users, except: [:show, :new, :create]
  end

  resources :quizzes, only: [:show, :index] do
    resources :questions, only: :create do
      post :start, on: :collection
    end
  end

  resources :results, only: :show

  get 'dashboard', to: 'dashboard#index'
  get 'histories', to: 'histories#index'
  get 'popular', to: 'popular#index'
  get 'search', to: 'search#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: 'home#index'
end

app/views/shared/_category_thumbnails.html.slim
.row.py-3
  - categories.each do |category|
    .col-md-4
      .card.mb-4.box-shadow
        = link_to quiz_path(category)
          = image_tag(category.image_url(:medium), class: "card-img-top")
        .card-body
          p.card-text.quiz-name__list = category.name
          .d-flex.justify-content-between.align-items-center
            .btn-group
              = link_to quiz_path(category)
                button.btn.btn-sm.btn-outline-secondary type="button" Play Now
            .div.text-right
              small.text-muted = pluralize(category.total_questions, "question")
              - if category.try(:count).present?
                small.text-muted style="display:block;margin-top:-5px" = pluralize(category.count, "play")

app/views/shared/_form_errors.html.slim
- if data.errors.any?
  .alert.alert-danger.alert-dismissible.fade.show role="alert" 
    strong = "You've got #{pluralize(data.errors.count, "error")}"
    ul.error_list
      - data.errors.full_messages.each do |message|
        li = message
    button.close aria-label="Close" data-dismiss="alert" type="button" 
      span aria-hidden="true" &times;

app/views/shared/_form_header.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 = title
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.mr-2
      = link_to backlink, class: "btn btn-sm btn-outline-secondary"
        | Cancel

app/views/shared/_pagination.html.slim
= paginate object, window: 1

app/views/shared/_result_list.html.slim
.quiz-show__container
  .table-responsive
    table.table.table-hover.table-bordered
      thead.thead-dark
        tr
          th scope="col" Question
          th.text-center scope="col" Your Answer
          th.text-center scope="col" Result
      tbody
        - results.each do |result|
          tr
            td == result.question.content
            td.text-center = result.answer
            td.text-center == true_or_false_icon(result.is_correct)

  = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"

  p.text-center
    a.btn.btn-sm.btn-sosmed.btn-fb href="https://www.facebook.com/sharer/sharer.php?u=#{result_url(results.first.category_token)}"
      i.fa.fa-facebook.pr-2
      | Share on Facebook
    | &nbsp;
    | &nbsp;
    a.btn.btn-sm.btn-sosmed.btn-tw href="https://twitter.com/home?status=#{result_url(results.first.category_token)}"
      i.fa.fa-twitter.pr-2
      | Tweet on Twitter

p.text-center
  = link_to 'PLAY AGAIN', quiz_path(results.first.category), class: "btn btn-success"