config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :dashboard  do
    resources :categories, except: :show
    resources :questions, except: :show
    resources :users, except: [:show, :new, :create]
  end

  resources :quizzes, only: [:show, :index] do
    resources :questions, only: :create do
      post :start, on: :collection
    end
  end

  resources :results, only: :show

  get 'dashboard', to: 'dashboard#index'
  get 'histories', to: 'histories#index'
  get 'popular', to: 'popular#index'
  get 'search', to: 'search#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: 'home#index'
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @histories = current_user.category_playings.order(id: :desc).page(params[:page]).per(10)
  end
end

app/views/histories/index.html.slim
h1 History of Playing Quizzes
p
  | &nbsp;
- if @histories.present?
  .table-responsive
    table.table.table-hover.table-bordered
      thead.thead-dark
        tr
          th.text-center scope="col" Date
          th scope="col" Quiz
          th.text-center scope="col" Question
          th.text-center scope="col" Correct
          th.text-center scope="col" Point
          th scope="col"
          th scope="col"

      tbody
        - @histories.each do |history|
          tr
            td.text-center = history.created_at.strftime("%Y-%m-%d %H:%M")
            td = history.category.name
            td.text-center = history.total_questions
            td.text-center = history.total_corrects
            td.text-center = history.point * 100
            td.text-center = link_to "Result", result_path(history.category_token), class: "btn btn-sm btn-primary"
            td.text-center = link_to "Play Again", quiz_path(history.category), class: "btn btn-sm btn-success"

  = render partial: "shared/pagination", locals: { object: @histories }
- else
  p
  h3.text-center It looks like you've never played quiz
  p.text-center
    = link_to "PLAY NOW", quizzes_path, class: "btn btn-primary"