config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :dashboard  do
    resources :categories, except: :show
    resources :questions, except: :show
    resources :users, except: [:show, :new, :create]
  end

  resources :quizzes, only: [:show, :index] do
    resources :questions, only: :create do
      post :start, on: :collection
    end
  end

  resources :results, only: :show

  get 'dashboard', to: 'dashboard#index'
  get 'histories', to: 'histories#index'
  get 'popular', to: 'popular#index'
  get 'search', to: 'search#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: 'home#index'
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, :answer, :position, presence: true

  belongs_to :category
  has_many :question_answers

  scope :published, -> { where(published: true) }
  scope :by_position, -> { order(position: :asc) }

  def check_correct_answer?(input)
    the_answer = answer.to_s.downcase
    input      = input.to_s.downcase

    return true if the_answer == input

    set_to_number(the_answer) == set_to_number(input)
  end

  private

  def set_to_number(string)
    number = NumbersInWords.in_numbers(string)

    if number.is_a?(Float) || number.is_a?(Integer)
      result = number
    else
      result = string
    end

    return string if result == 0

    result
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < DashboardController
  before_action :get_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.latest.page(params[:page]).per(10)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to dashboard_categories_path, notice: 'Quiz was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to dashboard_categories_path, notice: 'Quiz was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to dashboard_categories_path, notice: 'Quiz was successfully deleted.'
  end

  private
  
  def get_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, :published, :image, :remove_image)
  end
end

app/controllers/dashboard/questions_controller.rb
class Dashboard::QuestionsController < DashboardController
  before_action :get_question, only: [:edit, :update, :destroy]

  def index
    if params[:category_id].present?
      category = Category.find(params[:category_id])
      questions = category.questions.by_position
    else
      questions = Question.order(updated_at: :desc)
    end

    @questions = questions.page(params[:page]).per(10)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to dashboard_questions_path, notice: 'Quiz question was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to dashboard_questions_path, notice: 'Quiz question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to dashboard_questions_path, notice: 'Quiz question was successfully deleted.'
  end

  private
  
  def get_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:category_id, :content, :answer, :published, :position)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < DashboardController
  before_action :get_user, only: [:edit, :update, :destroy]

  def index
    if params[:role].present?
      users = User.where(role: params[:role])
    else
      users = User.order(updated_at: :desc)
    end
    @users = users.page(params[:page]).per(10)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to dashboard_users_path, notice: 'User was successfully deleted.'
  end

  private
  
  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_role

  layout "dashboard"

  def index
  end

  private

  def authenticate_role
    if current_user.role != 'admin'
      return redirect_to root_path, alert: 'You not have authorization'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout false

  before_action :authenticate_user!
  before_action :get_category_and_questions, only: [:start, :create]

  def start
    @next_page = 2
  end

  def create
    save_question_answer

    if @questions.present?
      @next_page = @questions.current_page + 1
      render "start"
    else
      save_category_playing
      @results = QuestionAnswer.where(category_token: params[:category_token]).order(id: :asc)
      render "_result"
    end
  end

  private

  def get_category_and_questions
    @category   = Category.published.find(params[:quiz_id])
    @questions  = @category.questions.published.by_position.page(params[:page]).per(1)
  end

  def save_question_answer
    question = @category.questions.find(params[:question_id])

    question_answer = QuestionAnswer.new(question_answer_params)
    question_answer.user = current_user
    question_answer.category_id = params[:quiz_id]
    question_answer.is_correct  = question.check_correct_answer?(params[:answer]).to_s
    question_answer.save
  end

  def save_category_playing
    total_questions = @questions.total_count
    total_corrects  = QuestionAnswer.where(category_token: params[:category_token]).where(is_correct: true).count

    category_playing                  = CategoryPlaying.new
    category_playing.category         = @category
    category_playing.user             = current_user
    category_playing.category_token   = params[:category_token]
    category_playing.total_questions  = total_questions
    category_playing.total_corrects   = total_corrects
    category_playing.point            = total_corrects.fdiv(total_questions).round(2)
    category_playing.save
  end

  def question_answer_params
    params.permit(:category_id, :question_id, :answer, :category_token)
  end
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/views/dashboard/questions/_form.html.slim
= render partial: "shared/form_errors", locals: { data: question }
= form_for [:dashboard, question] do |f|
  .mb-3
    = f.label :category_id, "Quiz"
    = f.collection_select(:category_id, Category.all.published.by_name, :id, :name, { prompt: "-- Select Category --" }, { class: "form-control", required: true })

  .mb-3
    = f.label :content, "Question"
    = f.cktext_area :content, required: true

  .mb-3
    = f.label :answer
    = f.text_field :answer, class: "form-control", required: true

  .mb-3
    = f.label :position
    = f.text_field :position, class: "form-control", required: true, type: "number", min: 1, max: 100, placeholder: "only number"

  .mb-3
    label
      = f.check_box :published
      | &nbsp; Set to published?

  hr.mb-4

  .mb-3
    = f.submit class: "btn btn-primary"

app/views/dashboard/questions/edit.html.slim
= render partial: "shared/form_header", locals: { title: "Edit Quiz Question", backlink: dashboard_questions_path }
= render partial: 'form', locals: { question: @question }

app/views/dashboard/questions/index.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 Quiz Questions
  .btn-toolbar.mb-2.mb-md-0
    .mr-2
      button.btn.btn-sm.btn-outline-secondary.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" Quizzes
      .dropdown-menu.dropdown-menu-sm
        - Category.by_name.each do |category|
          = link_to category.name, dashboard_questions_path(category_id: category.id), class: "dropdown-item dropdown-item-sm"
    = link_to new_dashboard_question_path, class: "btn btn-sm btn-outline-secondary"
      | Create

- if @questions.present?
  .table-responsive
    table.table.table-hover.table-bordered
      thead.thead-dark
        tr
          th scope="col" Quiz
          th scope="col" Question
          th.text-center scope="col" Answer
          th.text-center scope="col" Position
          th.text-center scope="col" Published
          th scope="col"
          th scope="col"
      tbody
        - @questions.each do |question|
          tr
            td = question.category.name
            td == question.content
            td.text-center = question.answer
            td.text-center = question.position
            td.text-center == true_or_false_icon(question.published)
            td.text-center
              = link_to "Edit", edit_dashboard_question_path(question), class: "btn btn-warning btn-sm", role: "button"
            td.text-center
              = link_to "Delete", dashboard_question_path(question), method: :delete, data: { confirm: 'Are you sure want to delete?' }, class: "btn btn-danger btn-sm", role: "button"

  = render partial: "shared/pagination", locals: { object: @questions }

app/views/dashboard/questions/new.html.slim
= render partial: "shared/form_header", locals: { title: "Create Quiz Question", backlink: dashboard_questions_path }
= render partial: 'form', locals: { question: @question }